version: '3'
services:
  app:
    container_name: gym-webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    environment:
      - APP_ENV=development
    depends_on:
      - db
    env_file:
      - .env 

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
